### ISSUE TITLE
How do you evaluate your model performance?

### ISSUE THREAD

**Issue by JunwenBai** [Fraser-Greenlee/T5-VAE#1]
I wonder how you evaluate the T5-VAE? From your description "Though the intermediate values are good, just randomly sampling from the latent space occasionally produces invalid outputs", it seems to work NOT very well? And there is no evaluation metric so far? Do you have a paper to describe more of this model? I read the blog, but overall it is still a bit vague to me.

**Comment by Fraser-Greenlee** [comment]
Hi Junwen, thank you for adding an issue!

I mainly evaluated performance using the regularising loss & NLL decoder loss on test sequences.
These sequences were generally structured sequences like Python code.
I was just trying to find a way to mitigate posterior collapse in a large transformer model which this does fix.
With some improvements to the architecture, I think this could become a versatile tool for sequence editing similar to how VAEs trained on images are used in the FaceApp.

For exactly how effective it is, compared to posterior collapse (or using a small model) it is way more effective but I have not done a fair test on a standard dataset to truly quantify its performance. The code dataset the model was trained on doesn't give a great spread of samples so it's hard to say how effective that makes it.
In general, it seems to be able to learn semantic rules given enough data but I fear the model isn't very efficient.
I'm going to be trying out using a Funnel-Transformer encoder next time to see if it can more efficiently compress the sequences.

I think it needs to be tested on a standard dataset like the Zinc dataset used in the Grammar VAE paper for a more fair comparison.
The blog is vague, I want to come out with a paper for it but at the moment I'm focusing on making some neat examples to see how far this can go.

Please let me know if you can think of any improvements to the architecture, plus if you wanna collaborate on producing a paper for this I think there's a ton of untapped potential here.

**Comment by JunwenBai** [comment]
Hi, Fraser,
I think your view is very profound. I have similar senses that the latent code from VAE is the key for reasoning. But in practice, so far the deterministic models still perform better and more stably on many domains (e.g. on huggingface, almost all of the uploaded models are deterministic ones). Nevertheless, using transformer might be a game-changer. So I'm exploring transformer+VAE a bit. Most existing seq VAE models are built on top of RNNs, while not many works combine transformer and VAE. Of course, there are many technical issues to address and I think your model's performance on python assignment codes is already very incredible and address many of them.
There are some existing papers in this field already, for instance, [Transformer VAE](https://mip-frontiers.eu/2020/08/20/transformer-vae.html), [T-CVAE](https://www.ijcai.org/Proceedings/2019/0727.pdf), [VT](https://arxiv.org/pdf/2003.12738.pdf), though these works are more of less domain-specific. If you are looking for some common sequence learning applications, you may look into these papers.
I'm definitely interested in working on a paper, though I'm quite new in this field and still learning. T_T We can keep in touch on GitHub or via emails. I'll let you know if I have any solid progress. :)

**Comment by Fraser-Greenlee** [comment]
I'm glad to meet someone who's thinking along the same lines!
Thank you, I'll check those papers out, please send me an email at fraser.greenlee@mac.com or just reply here if you want!

Currently I'm making a music generator by training T5-VAE with [LakhNES](https://chrisdonahue.com/LakhNES/) data to make an [ArtBreeder](https://www.artbreeder.com)-esc tool for music generation.
