### ISSUE TITLE
CommandException: No URLs matched: gs://fras/xxxx

### ISSUE THREAD

**Issue by JunwenBai** [Fraser-Greenlee/T5-VAE#2]
Loading issues, e.g. CommandException: No URLs matched: gs://fras/python_state_changes.txt. How to address this?

**Comment by Fraser-Greenlee** [comment]
Whoops I'll add this back!

**Comment by Fraser-Greenlee** [comment]
That should be it added.

**Comment by JunwenBai** [comment]
Hi, Fraser,

Thx for the quick reply! I have downloaded python_state_changes.txt, but other files are missing as well. Do you mind uploading those as well (basically the ones in "get_sample_data.sh")? Especially "gs://fras/python_assignments_autoencoder".
`CommandException: No URLs matched: gs://fras/python_assignments_autoencoder`
`CommandException: No URLs matched: gs://fras/250k_rndm_zinc_drugs_clean.txt`
`CommandException: No URLs matched: gs://fras/zinc_drugs`
`CommandException: No URLs matched: gs://fras/python_state_changes`

I hope to get a better sense of the code. So running through the datasets would be very helpful to me. Thx!

**Comment by JunwenBai** [comment]
Hi, Fraser,
Do you still plan to upload these files or folders? Thx!
Best

**Comment by Fraser-Greenlee** [comment]
I've had a look around and unfortunatley I deleted them a while ago.
You can find the zinc dataset [here](https://github.com/jonathanyin12/grammarVAE), modify [this](https://github.com/jonathanyin12/grammarVAE/blob/429bea166d62e8c0adecd8cdda481ea7fed1e01b/make_zinc_dataset_str.py#L7) script to get a raw text version.
For the other datasets they aren't very different from the python_state_changes.txt (plus they've been deleted and are awkward to recreate).

**Comment by JunwenBai** [comment]
Thx for the reply! That's fine. I just wanted to play with python_assignments. haha
Btw, I saw "train_t5_vae_py_code.sh" uses "python_assign.txt". Is it the same as "python_state_changes.txt" or a different .txt?

**Comment by Fraser-Greenlee** [comment]
They should be interchangeable, the training script is supposed to train on a [LineByLineTextDataset](https://github.com/huggingface/transformers/blob/a16e568f22a4d07813ba76343309ec20096115a5/src/transformers/data/datasets/language_modeling.py#L92) which just means it takes a text file as input and learns to auto-encode each line.
Just make sure you've got a sensible [sequence size](https://github.com/Fraser-Greenlee/T5-VAE/blob/master/train_t5_vae_py_code.sh#L26).

**Comment by JunwenBai** [comment]
Cool. So in expectation, by training on "python_state_changes.txt", I should achieve that "interpolating effect" between "x = a - 1" and "x = a + 10 * 2" as well?

**Comment by Fraser-Greenlee** [comment]
Should do!
