### ISSUE TITLE
No such file or directory: 'python_assignments_autoencoder/args.txt'

### ISSUE THREAD

**Issue by TheWoodKidJr** [Fraser-Greenlee/T5-VAE#3]
Hi, i've an issue, where can i find the file which corresponds to this :
No such file or directory: 'python_assignments_autoencoder/args.txt'

thanks in advance

**Comment by Fraser-Greenlee** [comment]
Hmmmm, is this from the [Colab doc](https://github.com/Fraser-Greenlee/T5-VAE/blob/a65681bbccff6b60c46919f9faacfb458424de2a/Colab_T5_VAE.ipynb?short_path=5a96c56#L80)?
Unfortunately I've left the training code for a lot of experiments that I can no longer run.
My only advice for now is just to run what works and look at the code to see what you can get out of it.

I'm off work next week so I'll be coming out with a new release of this codebase which will be bug free & show how to condition other models on your T5-VAE latent codes. This should allow arranging the latent space in terms of properties of the text (sentiment regression, topic classification, author, etc).
